name: "deploy build"

on:
  workflow_call:
    inputs:
      job_name:
        required: true
        type: string
        default: "Deploy React.JS to Azure Web App"
      runs_on:
        required: true
        type: string
        default: ubuntu-latest
      artifacts_name:
        required: true
        type: string
      artifacts_path:
        required: true
        type: string
      web_app_name:
        required: true
        type: string
      azure_webapp_package_path:
        required: true
        type: string
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE:
        required: true

jobs:
  application_deployment:
    name: ${{ inputs.job_name }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifacts_name }}
          path: ${{ inputs.artifacts_path }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ inputs.web_app_name }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ inputs.azure_webapp_package_path }}
